# Generated by Django 4.2.11 on 2024-09-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='month',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
