# Generated by Django 4.2.11 on 2024-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budgetitem_month_alter_budgetitem_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('ExpenseFixed', 'ExpenseFixed'), ('ExpenseVariable', 'ExpenseVariable'), ('Income', 'Income')], default='Expense', max_length=20),
        ),
    ]
