databases:
  - name: BudgetAppDB
    plan: free
    databaseName: budgetappdb_rb44
    user: budgetappdb_rb44_user

services:
  - type: web
    plan: free
    name: BudgetApp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BudgetAppDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4